version: '2'
services:
  echo:
    image: solsson/http-echo
    ports: 
      - 80

  sails_proxy:
    image: twhtanghk/sails_proxy
    ports:
      - 1337
    volumes:
      - ./data:/usr/src/app/data
      - ./production.coffee:/usr/src/app/config/env/production.coffee
    env_file: 
      - ../.env
